// قاعدة البيانات: 60 مشروب
const DRINKS = [
  // ===== ESPRESSO (الأصلية + الجديدة) =====
  {id:'espresso',name:'إسبريسو',category:'إسبرسو',subCategory:'سادة',family:'espresso',temperature:'hot',bean:'blend',strength:'قوي',description:'استخلاص مركز لقوام قوي وكريما ذهبية.',required:['بن','ماء'],optional:['سكر'],forbid:['حليب','كريمة','ثلج','نكهات'],presentation:{cup:'فنجان صغير'},notes:'يفضّل تحميص متوسط/غامق'},
  {id:'double',name:'دبل شوت',category:'إسبرسو',subCategory:'سادة',family:'espresso',temperature:'hot',bean:'blend',strength:'قوي جدًا',description:'شوتان من الإسبريسو لقوة أعلى.',required:['بن','ماء'],optional:['سكر'],forbid:['حليب','كريمة','ثلج'],presentation:{cup:'فنجان صغير'},notes:''},
  {id:'ristretto',name:'ريستريتو',category:'إسبرسو',subCategory:'سادة',family:'espresso',temperature:'hot',bean:'arabica',strength:'قوي',description:'استخلاص قصير بنكهة مركزة وأقل مرارة.',required:['بن','ماء'],optional:['سكر'],forbid:['حليب','ثلج'],presentation:{cup:'فنجان'},notes:''},
  {id:'lungo',name:'لونغو',category:'إسبرسو',subCategory:'سادة',family:'espresso',temperature:'hot',bean:'arabica',strength:'متوسط',description:'استخلاص أطول بماء أكثر وطعم أخف.',required:['بن','ماء'],optional:['سكر'],forbid:['حليب','ثلج'],presentation:{cup:'كوب صغير'},notes:''},
  {id:'americano',name:'أمريكانو',category:'إسبرسو',subCategory:'سادة بالماء',family:'espresso',temperature:'hot',bean:'arabica',strength:'متوسط',description:'إسبريسو مع ماء ساخن لطعم نظيف.',required:['بن','ماء'],optional:['سكر'],forbid:['حليب','كريمة','ثلج'],presentation:{cup:'كوب حراري'},notes:''},
  {id:'long_black',name:'لونغ بلاك',category:'إسبرسو',subCategory:'سادة بالماء',family:'espresso',temperature:'hot',bean:'arabica',strength:'متوسط-قوي',description:'ماء ثم إسبريسو فوقه للحفاظ على الكريما.',required:['بن','ماء'],optional:['سكر'],forbid:['حليب','ثلج'],presentation:{cup:'كوب'},notes:''},
  {id:'macchiato',name:'ماكياتو',category:'إسبرسو',subCategory:'لمسة رغوة',family:'espresso',temperature:'hot',bean:'arabica',strength:'قوي',description:'إسبريسو مع نقطة رغوة فقط.',required:['بن','رغوة'],optional:[],forbid:['حليب كثير','ثلج','كريمة'],presentation:{cup:'فنجان'},notes:''},
  {id:'cortado',name:'كورياتو',category:'إسبرسو',subCategory:'قليل الحليب',family:'espresso',temperature:'hot',bean:'arabica',strength:'متوسط-قوي',description:'توازن متساوٍ بين الإسبريسو والحليب الساخن.',required:['بن','حليب'],optional:['سكر'],forbid:['كريمة','ثلج'],presentation:{cup:'كوب صغير'},notes:''},
  {id:'cappuccino',name:'كابتشينو',category:'إسبرسو',subCategory:'حليب + رغوة',family:'espresso',temperature:'hot',bean:'arabica',strength:'متوسط',description:'إسبريسو مع حليب مبخر ورغوة كثيفة.',required:['بن','حليب','رغوة'],optional:['كاكاو','سكر','قرفة'],forbid:['ثلج','كريمة ثقيلة'],presentation:{cup:'كوب 200مل'},notes:''},
  {id:'latte',name:'لاتيه',category:'إسبرسو',subCategory:'حليب ناعم',family:'espresso',temperature:'hot',bean:'arabica',strength:'خفيف',description:'إسبريسو مع حليب مبخر ورغوة خفيفة.',required:['بن','حليب'],optional:['فانيلا','كراميل','بندق','سكر'],forbid:['كريمة','ثلج'],presentation:{cup:'كوب سيراميك'},notes:''},
  {id:'mocha_hot',name:'موكا (Mocha – ساخن)',category:'إسبرسو',subCategory:'شوكولاتة + حليب',family:'espresso',temperature:'hot',bean:'blend',strength:'متوسط',description:'إسبريسو مع شوكولاتة وحليب مبخر.',required:['بن','شوكولاتة','حليب'],optional:['سكر','كريمة خفيفة'],forbid:['ثلج','توابل'],presentation:{cup:'كوب'},notes:''},
  {id:'latte_macchiato',name:'لاتيه ماكياتو (Latte Macchiato)',category:'إسبرسو',subCategory:'حليب مُتوَّج بالشوت',family:'espresso',temperature:'hot',bean:'arabica',strength:'خفيف',description:'حليب ورغوة خفيفة مع تتويج شوت فوق.',required:['حليب','رغوة','بن'],optional:['فانيلا'],forbid:['ثلج','كريمة'],presentation:{cup:'كوب زجاجي'},notes:''},
  {id:'dry_cappuccino',name:'كابتشينو دراي (Dry Cappuccino)',category:'إسبرسو',subCategory:'رغوة كثيفة وسائل قليل',family:'espresso',temperature:'hot',bean:'arabica',strength:'متوسط',description:'إسبريسو مع رغوة كثيفة وسائل حليب قليل جدًا.',required:['بن','رغوة'],optional:['قرفة','كاكاو بودرة','سكر'],forbid:['ثلج','كريمة','حليب كثير'],presentation:{cup:'كوب 200مل'},notes:''},
  {id:'breve',name:'بريفيه (Breve)',category:'إسبرسو',subCategory:'نصف-نصف (كريمة خفيفة)',family:'espresso',temperature:'hot',bean:'arabica',strength:'متوسط',description:'إسبريسو مع نصف-نصف لقوام أغنى.',required:['بن','كريمة خفيفة'],optional:['فانيلا خفيفة'],forbid:['ثلج'],presentation:{cup:'كوب'},notes:''},
  {id:'espresso_romano',name:'إسبريسو رومانو (Espresso Romano)',category:'إسبرسو',subCategory:'لمسة ليمون',family:'espresso',temperature:'hot',bean:'arabica',strength:'قوي',description:'إسبريسو يُقدّم مع لمسة قشر ليمون.',required:['بن','ليمون'],optional:['سكر'],forbid:['حليب','كريمة'],presentation:{cup:'فنجان صغير'},notes:''},
  {id:'flat_white',name:'فلات وايت (Flat White)',category:'إسبرسو',subCategory:'مايكروفوم',family:'espresso',temperature:'hot',bean:'arabica',strength:'متوسط',description:'إسبريسو بحليب مايكروفوم ملمس حريري ونسبة حليب أقل من اللاتيه.',required:['بن','حليب'],optional:['رغوة','سكر'],forbid:['ثلج','كريمة'],presentation:{cup:'كوب سيراميك'},notes:''},
  {id:'piccolo',name:'بيكولو لاتيه (Piccolo Latte)',category:'إسبرسو',subCategory:'ريستريتو + حليب',family:'espresso',temperature:'hot',bean:'arabica',strength:'متوسط-قوي',description:'شوت ريستريتو قصير مع قليل من الحليب.',required:['ريستريتو','حليب'],optional:['سكر'],forbid:['ثلج','كريمة'],presentation:{cup:'كوب صغير'},notes:''},
  {id:'dirty_hot',name:'ديرتي كوفي (ساخن)',category:'إسبرسو',subCategory:'شوت فوق حليب ساخن',family:'espresso',temperature:'hot',bean:'arabica',strength:'متوسط',description:'حليب ساخن يُصب فوقه شوت إسبريسو.',required:['حليب','بن'],optional:['فانيلا خفيفة'],forbid:['شوكولاتة'],presentation:{cup:'كوب'},notes:''},

  // ===== BREW / FILTER =====
  {id:'v60',name:'V60 ترشيح',category:'ترشيح',subCategory:'فلتر ورقي',family:'brew',temperature:'hot',bean:'arabica',strength:'متوسط-خفيف',description:'ترشيح يدوي يبرز النكهات النظيفة.',required:['بن','ماء'],optional:['سكر','عسل'],forbid:['حليب','كريمة','نكهات','ثلج'],presentation:{cup:'كوب زجاجي'},notes:''},
  {id:'chemex',name:'كيمكس',category:'ترشيح',subCategory:'فلتر سميك',family:'brew',temperature:'hot',bean:'arabica',strength:'متوسط-خفيف',description:'قوام نقي بفضل الفلتر السميك.',required:['بن','ماء'],optional:['سكر'],forbid:['حليب','كريمة','ثلج'],presentation:{cup:'سيرفر + كوب'},notes:''},
  {id:'kalita',name:'كاليتا ويف',category:'ترشيح',subCategory:'قاع مسطح',family:'brew',temperature:'hot',bean:'arabica',strength:'متوسط-خفيف',description:'توازن أفضل بفضل القاع المسطح.',required:['بن','ماء'],optional:['سكر'],forbid:['حليب','كريمة','ثلج'],presentation:{cup:'كوب'},notes:''},
  {id:'siphon',name:'سايفون',category:'ترشيح',subCategory:'تفريغ بالضغط',family:'brew',temperature:'hot',bean:'arabica',strength:'متوسط',description:'مسرح بصري ونكهة نقية.',required:['بن','ماء'],optional:['سكر'],forbid:['حليب','كريمة'],presentation:{cup:'كوب'},notes:''},
  {id:'french_press',name:'فرنش برس',category:'ترشيح',subCategory:'غمر',family:'brew',temperature:'hot',bean:'arabica',strength:'متوسط',description:'غمر كامل لقوام أثقل.',required:['بن','ماء'],optional:['حليب قليل','سكر'],forbid:['كريمة','ثلج'],presentation:{cup:'كوب'},notes:''},
  {id:'aeropress',name:'أيروبريس',category:'ترشيح',subCategory:'ضغط يدوي',family:'brew',temperature:'hot',bean:'arabica',strength:'متوسط',description:'أداة مرنة لاستخلاص سريع.',required:['بن','ماء'],optional:['سكر'],forbid:['حليب','كريمة'],presentation:{cup:'كوب'},notes:''},
  {id:'moka_pot',name:'موكا بوت (Moka Pot)',category:'ترشيح',subCategory:'موقد / ضغط بخار',family:'brew',temperature:'hot',bean:'robusta',strength:'متوسط-قوي',description:'تحضير على الموقد بنكهة مركزة قريبة من الإسبريسو.',required:['بن','ماء'],optional:['سكر'],forbid:['حليب','نكهات'],presentation:{cup:'كوب صغير'},notes:''},
  {id:'batch_brew',name:'باتش برو (Batch Brew)',category:'ترشيح',subCategory:'تقطير آلي',family:'brew',temperature:'hot',bean:'arabica',strength:'خفيف-متوسط',description:'تقطير آلي ثابت لاستخلاص نظيف ومتزن.',required:['بن','ماء'],optional:['سكر'],forbid:['حليب','كريمة','نكهات'],presentation:{cup:'كوب حراري'},notes:''},
  {id:'clever',name:'كليفر دريبر (Clever Dripper)',category:'ترشيح',subCategory:'غمر + ترشيح',family:'brew',temperature:'hot',bean:'arabica',strength:'متوسط',description:'مزيج غمر ثم ترشيح لنكهة واضحة ومتوازنة.',required:['بن','ماء'],optional:['سكر خفيف'],forbid:['حليب','كريمة','شوكولاتة'],presentation:{cup:'كوب'},notes:''},
  {id:'vietnamese_phin',name:'قهوة فيتنامية بفِلتر فين (ساخنة)',category:'ترشيح',subCategory:'فين (Vietnamese Phin)',family:'brew',temperature:'hot',bean:'robusta',strength:'متوسط',description:'ترشيح بطيء على الفين؛ يُستخدم معه قليل من الحليب المكثف.',required:['بن','ماء'],optional:['حليب مكثف'],forbid:['كريمة','شوكولاتة'],presentation:{cup:'كوب زجاجي'},notes:''},

  // ===== ICED / COLD =====
  {id:'iced_latte',name:'آيس لاتيه',category:'باردة',subCategory:'حليب + ثلج',family:'iced',temperature:'iced',bean:'arabica',strength:'خفيف',description:'حليب بارد مع إسبريسو وثلج بطبقات.',required:['بن','حليب','ثلج'],optional:['فانيلا','كراميل','بندق','سكر'],forbid:['رغوة كثيفة','كريمة'],presentation:{cup:'كوب شفاف طويل'},notes:''},
  {id:'iced_mocha',name:'آيس موكا',category:'باردة',subCategory:'شوكولاتة',family:'iced',temperature:'iced',bean:'blend',strength:'متوسط',description:'شوكولاتة مع حليب بارد وإسبريسو.',required:['بن','شوكولاتة','حليب','ثلج'],optional:['كريمة','سكر'],forbid:['توابل'],presentation:{cup:'كوب شفاف'},notes:''},
  {id:'cold_brew',name:'كولد برو',category:'باردة',subCategory:'نقع بارد',family:'iced',temperature:'iced',bean:'arabica',strength:'متوسط',description:'نقع بارد طويل لحموضة أقل.',required:['بن','ماء','ثلج'],optional:['حليب','عسل','فانيلا'],forbid:['كريمة ثقيلة','شوكولاتة'],presentation:{cup:'كوب زجاجي'},notes:''},
  {id:'spanish_ice',name:'سبانيش آيس لاتيه',category:'باردة',subCategory:'محلّى',family:'iced',temperature:'iced',bean:'arabica',strength:'خفيف-متوسط',description:'حليب مكثف محلى + حليب + إسبريسو + ثلج.',required:['حليب مكثف','حليب','بن','ثلج'],optional:['فانيلا','كراميل'],forbid:['كريمة','شوكولاتة'],presentation:{cup:'كوب شفاف'},notes:''},
  {id:'dirty_ice',name:'ديرتي كوفي (بارد)',category:'باردة',subCategory:'شوت فوق حليب بارد',family:'iced',temperature:'iced',bean:'arabica',strength:'متوسط',description:'حليب بارد مع شوت إسبريسو فوقه.',required:['حليب','بن','ثلج'],optional:['فانيلا','سكر'],forbid:['كريمة','شوكولاتة'],presentation:{cup:'كوب شفاف'},notes:''},
  {id:'frappuccino',name:'فرابتشينو قهوة',category:'باردة',subCategory:'مخلوط',family:'iced',temperature:'iced',bean:'blend',strength:'خفيف-متوسط',description:'مشروب مخلوط بالقهوة والحليب والثلج.',required:['بن','حليب','ثلج'],optional:['شوكولاتة','كريمة','كراميل'],forbid:['توابل تراثية'],presentation:{cup:'كوب بغطاء'},notes:''},
  {id:'iced_americano',name:'آيس أمريكانو (Iced Americano)',category:'باردة',subCategory:'إسبريسو + ماء + ثلج',family:'iced',temperature:'iced',bean:'arabica',strength:'خفيف-متوسط',description:'إسبريسو مع ماء بارد وثلج لطعم نقي.',required:['بن','ماء','ثلج'],optional:['سكر خفيف'],forbid:['حليب','كريمة'],presentation:{cup:'كوب شفاف'},notes:''},
  {id:'iced_white_mocha',name:'وايت موكا آيس (Iced White Mocha)',category:'باردة',subCategory:'شوكولاتة بيضاء',family:'iced',temperature:'iced',bean:'blend',strength:'متوسط',description:'إسبريسو مع شوكولاتة بيضاء وحليب وثلج.',required:['بن','شوكولاتة بيضاء','حليب','ثلج'],optional:['كريمة','فانيلا'],forbid:['توابل تراثية'],presentation:{cup:'كوب شفاف'},notes:''},
  {id:'cold_foam_cb',name:'كولد برو برغوة باردة (Cold Foam Cold Brew)',category:'باردة',subCategory:'كولد برو + رغوة باردة',family:'iced',temperature:'iced',bean:'arabica',strength:'متوسط',description:'كولد برو مع رغوة باردة مخفوقة من الحليب.',required:['بن منقوع بارد','ثلج','رغوة'],optional:['فانيلا'],forbid:['شوكولاتة كثيفة'],presentation:{cup:'كوب زجاجي'},notes:''},
  {id:'nitro_cb',name:'نيترو كولد برو (Nitro Cold Brew)',category:'باردة',subCategory:'مشبع بالنيتروجين',family:'iced',temperature:'iced',bean:'arabica',strength:'متوسط',description:'كولد برو نيترو يُقدّم غالبًا دون إضافات.',required:['بن منقوع بارد','نيترو'],optional:[],forbid:['حليب','سكر','شوكولاتة'],presentation:{cup:'كوب'},notes:''},
  {id:'espresso_tonic',name:'إسبرسو تونِك (Espresso Tonic)',category:'باردة',subCategory:'شوت + تونك + ثلج',family:'iced',temperature:'iced',bean:'arabica',strength:'متوسط',description:'شوت إسبريسو فوق مشروب تونك وثلج.',required:['بن','تونك','ثلج'],optional:['شريحة ليمون'],forbid:['حليب','كريمة'],presentation:{cup:'كوب شفاف'},notes:''},

  // ===== TRADITION =====
  {id:'saudi',name:'قهوة سعودية',category:'تراثية',subCategory:'هيل',family:'tradition',temperature:'hot',bean:'arabica',strength:'خفيف',description:'قهوة عربية خفيفة بالهيل وقد يضاف الزعفران.',required:['بن فاتح','هيل','ماء'],optional:['زعفران','قرنفل'],forbid:['حليب','شوكولاتة','ثلج','سكر'],presentation:{cup:'دلة + فناجين'},notes:'تقدم مع تمر'},
  {id:'turkish',name:'قهوة تركية',category:'تراثية',subCategory:'سادة',family:'tradition',temperature:'hot',bean:'arabica',strength:'قوي',description:'غلي خفيف مع رغوة سطحية كثيفة.',required:['بن ناعم جدًا','ماء'],optional:['سكر','هيل'],forbid:['حليب','كريمة','ثلج'],presentation:{cup:'فنجان صغير'},notes:''},
  {id:'bosnian',name:'قهوة بوسنية',category:'تراثية',subCategory:'نحاسية',family:'tradition',temperature:'hot',bean:'arabica',strength:'متوسط-قوي',description:'تحضير نحاسي بطابع قريب من التركي.',required:['بن','ماء'],optional:['سكر'],forbid:['حليب','ثلج'],presentation:{cup:'دزفا + فناجين'},notes:''},
  {id:'ethiopian_ceremony',name:'قهوة إثيوبية',category:'تراثية',subCategory:'جلسة تقليدية',family:'tradition',temperature:'hot',bean:'arabica',strength:'متوسط',description:'تحميص وطحن وتخمير ضمن جلسة تقليدية.',required:['بن','ماء'],optional:['سكر'],forbid:['حليب','ثلج','شوكولاتة'],presentation:{cup:'أكواب صغيرة'},notes:''},
  {id:'adeni_milk',name:'قهوة عدنية بالحليب',category:'تراثية',subCategory:'هيل + حليب',family:'tradition',temperature:'hot',bean:'arabica',strength:'خفيف-متوسط',description:'قهوة بالحليب والهيل ولمسة زعفران اختيارية.',required:['بن','حليب','هيل'],optional:['زعفران خفيف','سكر'],forbid:['شوكولاتة','ثلج'],presentation:{cup:'كوب'},notes:''},
  {id:'greek',name:'قهوة يونانية (Greek)',category:'تراثية',subCategory:'ناعمة جدًا',family:'tradition',temperature:'hot',bean:'arabica',strength:'قوي',description:'تحضير قريب من التركي على نار هادئة.',required:['بن ناعم جدًا','ماء'],optional:['سكر حسب الدرجة'],forbid:['حليب','كريمة','ثلج'],presentation:{cup:'فنجان صغير'},notes:''},
  {id:'sudanese_ginger',name:'قهوة سودانية بالزنجبيل (جبنة)',category:'تراثية',subCategory:'زنجبيل',family:'tradition',temperature:'hot',bean:'arabica',strength:'متوسط-قوي',description:'قهوة مع زنجبيل بطابع دافئ.',required:['بن','زنجبيل','ماء'],optional:['سكر'],forbid:['حليب','شوكولاتة'],presentation:{cup:'كوب'},notes:''},

  // ===== SIGNATURE =====
  {id:'spanish_latte',name:'سبانيش لاتيه',category:'تخصصية',subCategory:'محلّى بالحليب',family:'signature',temperature:'either',bean:'arabica',strength:'خفيف-متوسط',description:'حليب مُحلّى بإسبريسو بطبقات جذابة.',required:['بن','حليب','حليب مكثف'],optional:['فانيلا','كراميل'],forbid:['شوكولاتة','ثلج (في الساخن)'],presentation:{cup:'شفاف'},notes:''},
  {id:'pistachio_latte',name:'بستاشيو لاتيه',category:'تخصصية',subCategory:'مكسرات',family:'signature',temperature:'either',bean:'arabica',strength:'خفيف-متوسط',description:'حليب مع معجون فستق وإسبريسو.',required:['بن','حليب','فستق'],optional:['فانيلا','سكر'],forbid:['شوكولاتة'],presentation:{cup:'كوب'},notes:''},
  {id:'saffron_latte',name:'زعفران لاتيه',category:'تخصصية',subCategory:'زهري',family:'signature',temperature:'either',bean:'arabica',strength:'خفيف-متوسط',description:'لاتيه بلمسة زعفران عطرية.',required:['بن','حليب','زعفران'],optional:['سكر','فانيلا'],forbid:['شوكولاتة'],presentation:{cup:'كوب'},notes:''},
  {id:'caramel_latte',name:'كراميل لاتيه',category:'تخصصية',subCategory:'محلّى',family:'signature',temperature:'either',bean:'arabica',strength:'خفيف-متوسط',description:'لاتيه مع صوص كراميل.',required:['بن','حليب','كراميل'],optional:['فانيلا','سكر'],forbid:['شوكولاتة'],presentation:{cup:'كوب'},notes:''},
  {id:'honey_latte',name:'عسل لاتيه',category:'تخصصية',subCategory:'محلّى طبيعي',family:'signature',temperature:'either',bean:'arabica',strength:'خفيف-متوسط',description:'لاتيه محلّى بالعسل للنعومة.',required:['بن','حليب','عسل'],optional:['فانيلا'],forbid:['شوكولاتة'],presentation:{cup:'كوب'},notes:''},
  {id:'salted_caramel',name:'سولتد كراميل لاتيه (Salted Caramel Latte)',category:'تخصصية',subCategory:'لمسة ملح بحري',family:'signature',temperature:'either',bean:'arabica',strength:'خفيف-متوسط',description:'لاتيه بكراميل ولمسة ملح بحري متوازنة.',required:['بن','حليب','كراميل','ملح'],optional:['فانيلا'],forbid:['شوكولاتة'],presentation:{cup:'كوب'},notes:''},
  {id:'rose_latte',name:'روز لاتيه (Rose Latte)',category:'تخصصية',subCategory:'شراب ورد',family:'signature',temperature:'either',bean:'arabica',strength:'خفيف',description:'لاتيه برائحة الورد الناعمة.',required:['بن','حليب','شراب ورد'],optional:['فانيلا خفيفة','سكر'],forbid:['شوكولاتة'],presentation:{cup:'كوب'},notes:''},
  {id:'hazelnut_latte',name:'بندق لاتيه (Hazelnut Latte)',category:'تخصصية',subCategory:'نكهة بندق',family:'signature',temperature:'either',bean:'arabica',strength:'خفيف-متوسط',description:'لاتيه بنكهة البندق.',required:['بن','حليب','بندق'],optional:['فانيلا'],forbid:['شوكولاتة ثقيلة'],presentation:{cup:'كوب'},notes:''},

  // ===== DESSERT =====
  {id:'affogato',name:'أفوجاتو',category:'حلويات',subCategory:'آيس كريم + شوت',family:'dessert',temperature:'either',bean:'arabica',strength:'متوسط',description:'سكوب آيس كريم يُسكب عليه إسبريسو.',required:['آيس كريم','بن'],optional:['شوكولاتة','مكسرات'],forbid:['حليب إضافي','ثلج'],presentation:{cup:'كأس حلوى'},notes:''},
  {id:'tiramisu_latte',name:'تيراميسو لاتيه',category:'حلويات',subCategory:'كريمة + كاكاو',family:'dessert',temperature:'either',bean:'blend',strength:'خفيف-متوسط',description:'لاتيه بحلة تيراميسو وكريمة.',required:['بن','حليب','كريمة','كاكاو'],optional:['سكر','فانيلا'],forbid:['ثلج (في الساخن)'],presentation:{cup:'كوب'},notes:''},
  {id:'bicerin',name:'بيتشيرين (Bicerin)',category:'حلويات',subCategory:'شوكولاتة + قهوة + كريمة',family:'dessert',temperature:'hot',bean:'blend',strength:'متوسط',description:'طبقات شوكولاتة ساخنة مع قهوة وكريمة.',required:['شوكولاتة','بن','كريمة'],optional:[],forbid:['ثلج'],presentation:{cup:'كأس حلوى'},notes:''},
  {id:'coffee_milkshake',name:'ميلكشيك قهوة (Coffee Milkshake)',category:'حلويات',subCategory:'بارد',family:'dessert',temperature:'iced',bean:'blend',strength:'خفيف',description:'ميلكشيك بآيس كريم وقهوة.',required:['بن','آيس كريم','حليب'],optional:['شوكولاتة','كراميل'],forbid:['توابل تراثية'],presentation:{cup:'كأس ميلكشيك'},notes:''},

  // ===== ALTERNATIVE =====
  {id:'decaf_latte',name:'ديكاف لاتيه',category:'بدائل',subCategory:'منزوع الكافيين',family:'alternative',temperature:'either',bean:'arabica',strength:'خفيف-متوسط',description:'لاتيه ببن منزوع الكافيين.',required:['ديكاف','حليب'],optional:['فانيلا','عسل'],forbid:['شوكولاتة'],presentation:{cup:'كوب'},notes:''},
  {id:'barley_coffee',name:'قهوة الشعير',category:'بدائل',subCategory:'بدون بن',family:'alternative',temperature:'either',bean:'none',strength:'خفيف',description:'مشروب شعير محمص بطابع قهوة.',required:['شعير محمص','ماء'],optional:['حليب نباتي','عسل'],forbid:['شوكولاتة ثقيلة'],presentation:{cup:'كوب'},notes:''}
];
